허리케인 박스타 입니다
woowacourse-code-review-study/java-chess pull request #7
Opened 2023-03-17 10:26 UTC by drunkenhw

2023-03-18 07:08 UTC, woo-chang reviewed
수고하셨습니다 :) 많이 배워갑니다 박스터 고수 👾

2023-03-18 07:08 UTC, woo-chang commented on README.md
> +            - [x] K: e
이런 정보도 알려주는거 너무 좋습니다 👍

2023-03-18 07:08 UTC, woo-chang commented on src/main/java/chess/controller/ChessController.java
> +public class ChessController {
컨트롤러가 너무 깔끔해서 읽기 편했어요 👍

2023-03-18 07:08 UTC, woo-chang commented on src/main/java/chess/controller/GameCommand.java
> +    }
각 enum이 move, end를 스트링으로 가지고

```java
public static GameCommand of(String input) {
    return Arrays.straem(GameCommand.values())
        .filter(command -> command.name.equalsIgnoreCase(input))
        .findFirst()
        .orElseThrow(() -> throw new IllegalArgumentException("잘못된 명령어를 입력했습니다."));
}
```
위와 같은 코드는 별로일까요? 🤔

2023-03-18 07:08 UTC, woo-chang commented on src/main/java/chess/domain/ChessGame.java
> +        this.color = Color.WHITE;
색에 따른 턴도 구분할 수 있게 구현해주셨네요 너무 좋은데요 👍

2023-03-18 07:08 UTC, woo-chang commented on src/main/java/chess/domain/board/Board.java
> +        throw new IllegalArgumentException("잘못된 위치를 입력했습니다");
`NIT`: 정말 사소한 부분입니다

```java
if (!boards.containsKey(position)) {
    throw new IllegalArgumentException("잘못된 위치를 입력했습니다");
}
return boards.get(position);
```

특정 조건일 때 예외를 발생시키는게 더 자연스러워보이는데, 박스터는 어떻게 생각하시나요?

2023-03-18 07:08 UTC, woo-chang commented on src/main/java/chess/domain/board/FileCoordinate.java
> +    H(8),
다른 분들도 동일한 리뷰를 남겼지만 a,b,c,d,e,f,g,h로 표현되어 있는만큼 `character` 사용은 어떻게 생각하시나요?

인덱스 계산도 편리합니다 ㅎㅎ..

2023-03-18 07:08 UTC, woo-chang commented on src/main/java/chess/domain/board/Position.java
> +        int rowStep = getStep(nowRankCoordinate, targetRankCoordinate);
`Position`에게 움직일 `column`과 `row`를 전달해서 움직인 `Position`을 반환하도록 하는건 어떨까요?

2023-03-18 07:08 UTC, woo-chang commented on src/main/java/chess/domain/board/Position.java
> +    }
별도로 메서드 분리를 하신 이유가 궁금합니다!

2023-03-18 07:08 UTC, woo-chang commented on src/main/java/chess/domain/board/RankCoordinate.java
> +    }
첫 위치라는 의미를 담기 위해 `isWhiteInitRank`, `isBlackInitRank`와 같이 수정하는건 어떻게 생각하시나요?

2023-03-18 07:08 UTC, woo-chang commented on src/main/java/chess/domain/piece/Piece.java
> +public abstract class Piece {
`Piece`들이 전체적으로 깔끔한 것 같아서 보기 좋은 것 같습니다 👍

2023-03-18 07:08 UTC, woo-chang commented on src/main/java/chess/view/PieceTypeView.java
> +    private final Class<? extends Piece> piece;
제네릭에서 배운 상한 제한을 활용할 수 있네요 너무 좋은데요 👍

2023-03-18 07:28 UTC, Choi-JJunho requested changes
허리케인 박스터🌀 안녕하세요
세부 구현로직은 눈이 핑핑 돌아서 못읽겠습니다.
TL;DR

코멘트가 도움이 되었으면 좋겠네요~

2023-03-18 07:28 UTC, Choi-JJunho commented on src/main/java/chess/domain/board/Board.java
> +        throw new IllegalArgumentException("잘못된 위치를 입력했습니다");
맵에서 해당하는 키값이 존재하지 않을 때 발생하는 Exception을 이용해보는건 어떨까요?

2023-03-18 07:28 UTC, Choi-JJunho commented on src/main/java/chess/controller/ChessController.java
> +            chessGame.movePieceTo(positions.get(0), positions.get(1));
만약 start가 입력된다면 positions에 대해 OutOfBound가 일어날 거 같네요~

2023-03-18 07:28 UTC, Choi-JJunho commented on src/main/java/chess/domain/board/Position.java
> +
개행

2023-03-18 07:28 UTC, Choi-JJunho commented on src/main/java/chess/domain/board/Position.java
> +        int targetRankCoordinate = targetPosition.getRow();
이미 File, Rank 만으로 해당 지점이라는 의미가 충분히 전달되는 것 같은데 Coordinate라는 단어가 들어가면서 과한 표현이 되는 것 같네요?

2023-03-18 07:28 UTC, Choi-JJunho commented on src/main/java/chess/domain/board/RankCoordinate.java
> +    }
동의합니다

2023-03-18 07:28 UTC, Choi-JJunho commented on src/main/java/chess/domain/piece/Direction.java
> +public enum Direction {
Direction 좋은데요?

2023-03-18 07:28 UTC, Choi-JJunho commented on src/main/java/chess/view/OutputView.java
> +    }
View가 도메인을 의존하면 어떤 문제가 발생할까요?

2023-03-18 07:28 UTC, Choi-JJunho commented on src/main/java/chess/view/PieceTypeView.java
> +public enum PieceTypeView {
PieceTypeView 좋은데요?

2023-03-18 07:28 UTC, Choi-JJunho commented on src/test/java/chess/domain/PositionFixture.java
> +public class PositionFixture {
Fixture 정리좀해주세요

2023-03-18 07:28 UTC, Choi-JJunho commented on src/test/java/chess/domain/board/BoardTest.java
> +@SuppressWarnings("NonAsciiCharacters")
좋은데요?

2023-03-18 07:28 UTC, Choi-JJunho commented on src/test/java/chess/domain/piece/PawnTest.java
> +    @CsvSource(value = {"B:TWO:true", "B:THREE:true", "A:TWO:false", "B:ONE:false", "C:THREE:false",
왜 애매하게 한줄 내려갔죠?

2023-03-18 07:28 UTC, Choi-JJunho commented on src/test/java/chess/domain/piece/QueenTest.java
> +    void 퀸이_움직일_수_있는지_알_수_있다(FileCoordinate fileCoordinate, RankCoordinate rankCoordinate, boolean expect) {
테스트명을 "어디에서 어디로 움직일 수 있는 지 알 수 있다" 라는 네이밍으로 표현해주면 좋을 것 같아요

2023-03-21 13:37 UTC, greeng00se reviewed
허리케인 슝슝슝?

2023-03-21 13:37 UTC, greeng00se commented on src/main/java/chess/controller/ChessController.java
> +        chessGame.movePieceTo(GameCommand.createPosition(source), GameCommand.createPosition(target));
GameCommand가 Poisition의 생성 책임을 가지고 있는 이유가 있을까요?

2023-03-21 13:37 UTC, greeng00se commented on src/main/java/chess/controller/GameCommand.java
> +    }
stream과 Enum의 name을 사용한다면 분기를 효과적으로 제거할 수 있을 것 같아요!

2023-03-21 13:37 UTC, greeng00se commented on src/main/java/chess/domain/board/BoardFactory.java
> +    private final static Map<Position, Piece> INIT_CHESS_BOARD = new HashMap<>();
private static final

2023-03-21 13:37 UTC, greeng00se commented on src/main/java/chess/domain/board/BoardFactory.java
> +            createRank(INIT_CHESS_BOARD, rankCoordinate);
static final 변수로 선언했는데 매개변수로 넘기는 이유가 있을까요?

2023-03-21 13:37 UTC, greeng00se commented on src/main/java/chess/domain/game/Turn.java
> +public class Turn {
turn 👍

2023-03-21 13:37 UTC, greeng00se commented on src/main/java/chess/domain/piece/King.java
> +    public Piece move() {
모든 Piece의 move 메서드가 자기 자신을 반환한다는게 명확하지 않은 것 같습니다

2023-03-21 13:37 UTC, greeng00se commented on src/main/java/chess/domain/piece/Pawn.java
> +        return new Pawn(this.getColor(), moveCount + 1);
폰 때문에 이렇게 작성하셨군요!

2023-03-21 13:37 UTC, greeng00se commented on src/test/java/chess/domain/piece/BishopTest.java
> +        assertThat(bishop.canMove(C_4, new Position(fileCoordinate, rankCoordinate), Color.EMPTY)).isEqualTo(expect);
다른 테스트코드와 같이 빈 칸으로 구분할 수 있을 것 같습니다

2023-03-21 13:37 UTC, greeng00se commented on src/test/java/chess/domain/position/PositionTest.java
> +        assertThat(reversePath).containsOnly(D_5, E_6);
박스터가 assertAll을 포기하다니..

2023-03-26 08:54 UTC, closed without merging